language: node_js
node_js:
 - "8"

branches:
 only:
  - develop

install:
- npm install

script:
- npm run-script build
- npm run-script coverage

before_deploy:
- ./scripts/prepare-deployment.sh

deploy:
- skip_cleanup: true
  provider: firebase
  except: functions
  on:
    branch: develop
  token:
    secure: "$FIREBASE_SECRET"
  project: "fir-project-3d2a4"

