language: node_js
node_js:
 - "8"

branches:
 only:
  - develop

install:
- npm install

script:
- npm run-script build
- npm run-script coverage
- npm install -g firebase-cli

before_deploy:
- ./scripts/prepare-deployment.sh

#deploy:
#- skip_cleanup: true
#  provider: firebase
#  except: functions
#  on:
#    branch: develop
#  token:
#    secure: "$FIREBASE_SECRET"
#  project: "fir-project-3d2a4"
#
after_success:
  - firebase deploy --project "fir-project-3d2a4" --token "$FIREBASE_SECRET" --except functions